#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/UserManagement
#    username: root
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl:auto: update
#    show-sql: true
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: akshaypandule7172@gmail.com
#    password: cksm rzpq hzqy mmev
#    properties:
#      mail:
#        smtp:
#          auth: true
#        sharttls:
#          enable: true
#          required: true
#
#user-api:
#  message:
#    Invalid: invalid credentials
#    notActivated: Account is Not Activated
#    succ: Success
#    InvalidEmail: invalid Email
#
#
#
#
#
#
#
